# Determinan Matrix

## Menggunakan library numpy

In [ ]:
import numpy as np

#example matrix di PPT
A = np.array([[2,3,-1], [1,0,5], [-1,5,4]])
print(A)

#menghitung determinan
det = np.linalg.det(A)

print("Determinan: ", round (det,2))

[[ 2  3 -1]
 [ 1  0  5]
 [-1  5  4]]
Determinan:  -82.0


## Tanpa Library Numpy

$$
A =
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix}
$$

$$
det(A) =
a \begin{vmatrix} e & f \\ h & i \end{vmatrix}
-
b \begin{vmatrix} d & f \\ g & i \end{vmatrix}
+
c \begin{vmatrix} d & e \\ g & h \end{vmatrix}
$$

In [14]:
def determinan(matrix):
    n = len(matrix)

    if n == 1:
        return matrix[0][0]

    if n == 2:
        return matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]

    det = 0
    for c in range(n):
        minor = [row[:c] + row[c+1:] for row in matrix[1:]]
        det += ((-1)**c) * matrix[0][c] * determinan(minor)

    return det


A = [
    [2, 3, -1],
    [1, 0, 5],
    [-1, 5, 4]
]

print("Determinan =", determinan(A))

Determinan = -82


# Naive Gaussian

## forward elimination

In [ ]:
import numpy as np

#example matrix di PPT
A = np.array([[6, -2, 2, 4], [12, -8, 6, 10], [3, -13, 9, 3], [-6, 4, 1, -18]])