# Determinan Matrix

## Menggunakan library numpy

In [1]:
import numpy as np

#example matrix di PPT
A = np.array([[2,3,-1], [1,0,5], [-1,5,4]])
print(A)

#menghitung determinan
det = np.linalg.det(A)

print("Determinan: ", round (det,2))

[[ 2  3 -1]
 [ 1  0  5]
 [-1  5  4]]
Determinan:  -82.0


## Tanpa Library Numpy

$$
A =
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix}
$$

$$
det(A) =
a \begin{vmatrix} e & f \\ h & i \end{vmatrix}
-
b \begin{vmatrix} d & f \\ g & i \end{vmatrix}
+
c \begin{vmatrix} d & e \\ g & h \end{vmatrix}
$$

In [14]:
def determinan(matrix):
    n = len(matrix)

    if n == 1:
        return matrix[0][0]

    if n == 2:
        return matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]

    det = 0
    for c in range(n):
        minor = [row[:c] + row[c+1:] for row in matrix[1:]]
        det += ((-1)**c) * matrix[0][c] * determinan(minor)

    return det


A = [
    [2, 3, -1],
    [1, 0, 5],
    [-1, 5, 4]
]

print("Determinan =", determinan(A))

Determinan = -82


# Naive Gaussian

## menjadikan matrix upper triangular
$$
\begin{bmatrix}
a_{11} & a_{12} & a_{13} & a_{14} \\
0 & a_{22} & a_{23} & a_{24} \\
0 & 0 & a_{33} & a_{34} \\
0 & 0 & 0 & a_{44}
\end{bmatrix}
$$


In [5]:
import numpy as np

def gaussian_elimination(A, b):
    n = len(b)

    print("Initial Matrix:")
    print(A)
    print("b =", b)
    print()

    # -------------------------
    # Forward Elimination
    # -------------------------
    for k in range(n-1):
        print(f"Step {k+1}: Eliminate x{k+1}")

        for i in range(k+1, n):

            factor = A[i][k] / A[k][k]
            print(f"R{i+1} = R{i+1} - ({factor}) * R{k+1}")

            for j in range(k, n):
                A[i][j] = A[i][j] - factor * A[k][j]

            b[i] = b[i] - factor * b[k]

        print("\nMatrix after step", k+1)
        print(A)
        print("b =", b)
        print("-"*40)

    # -------------------------
    # Backward Substitution
    # -------------------------
    print("\nBackward Substitution")

    x = np.zeros(n)

    x[n-1] = b[n-1] / A[n-1][n-1]
    print(f"x{n} =", x[n-1])

    for i in range(n-2, -1, -1):

        sum = b[i]

        for j in range(i+1, n):
            sum = sum - A[i][j] * x[j]

        x[i] = sum / A[i][i]

        print(f"x{i+1} =", x[i])

    return x


# -------------------------
# INPUT MATRIX (SAMA SEPERTI PPT)
# -------------------------

A = np.array([[6., -2., 2., 4.],
              [12., -8., 6., 10.],
              [3., -13., 9., 3.],
              [-6., 4., 1., -18.]])

b = np.array([16., 26., -19., -34.])

# solve
x = gaussian_elimination(A.copy(), b.copy())

print("\nFinal Solution:")
print(x)

Initial Matrix:
[[  6.  -2.   2.   4.]
 [ 12.  -8.   6.  10.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]]
b = [ 16.  26. -19. -34.]

Step 1: Eliminate x1
R2 = R2 - (2.0) * R1
R3 = R3 - (0.5) * R1
R4 = R4 - (-1.0) * R1

Matrix after step 1
[[  6.  -2.   2.   4.]
 [  0.  -4.   2.   2.]
 [  0. -12.   8.   1.]
 [  0.   2.   3. -14.]]
b = [ 16.  -6. -27. -18.]
----------------------------------------
Step 2: Eliminate x2
R3 = R3 - (3.0) * R2
R4 = R4 - (-0.5) * R2

Matrix after step 2
[[  6.  -2.   2.   4.]
 [  0.  -4.   2.   2.]
 [  0.   0.   2.  -5.]
 [  0.   0.   4. -13.]]
b = [ 16.  -6.  -9. -21.]
----------------------------------------
Step 3: Eliminate x3
R4 = R4 - (2.0) * R3

Matrix after step 3
[[ 6. -2.  2.  4.]
 [ 0. -4.  2.  2.]
 [ 0.  0.  2. -5.]
 [ 0.  0.  0. -3.]]
b = [16. -6. -9. -3.]
----------------------------------------

Backward Substitution
x4 = 1.0
x3 = -2.0
x2 = 1.0
x1 = 3.0

Final Solution:
[ 3.  1. -2.  1.]
